stages:
  - test
  - build_static_assets

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:latest

.js:
  image: node
  before_script:
    - git --version
    - node --version
    - npm --version
    - yarn --version
    - yarn

test:
  image: buildkite/puppeteer
  stage: test
  before_script:
    - apt-get update && apt-get install -y git
    - git --version
    - node --version
    - npm --version
    - yarn --version
    - yarn
  script:
    - yarn test

build_static_assets:
  extends: .js
  stage: build_static_assets
  script:
    - yarn build:prod
  artifacts:
    paths:
      - build/
