stages:
  - test

test:
  image: buildkite/puppeteer
  stage: test
  before_script:
    - apt-get update && apt-get install -y git
    - git --version
    - node --version
    - npm --version
    - yarn --version
    - yarn
  script:
    - yarn test
