name: push-to-mirror
on: [push]

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: 'https://gitlab.ebi.ac.uk/dlrice/uniprot-website.git'
          GIT_USERNAME: dlrice
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
